### ISSUE TITLE
Kermits 126: Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [defoebrand/Alien-Invasion#2]
- Consider working on the collider you've set up for the player and the ground, since the player sinks into the ground a bit and the enemies' bullets pass over his head.
- Using ES6 arrow function syntax can allow you to forgo the .bind() syntax you're using.

**Comment by defoebrand** [comment]
The different heights have actually set up natural skill level differences in that the citizen is normal mode, soldier is hard mode, and alien is easy mode :)

ES6 refactoring has been added
